### ISSUE TITLE
Pod "my-release-fn-fnlb-depl-8f8fcf476-4pvmh" is under "Back-off restarting failed container"

### ISSUE THREAD

**Issue by chatchai-komrangded** [fnproject/fn-helm#31] opened 2018-06-17 07:30 UTC
Hi,
  I tried to deploy fn sever on Kubernetest on OKE, but still facing the issue about "Back-off restarting failed container" Here's my Yaml file..

# Default values for Fn
imagePullPolicy: Always

# If non-null, will override the cluster name
nameOverride: ''

fn:
  service:
    port: 80
    type: LoadBalancer
    annotations: {}

fnlb:
  image: fnproject/fnlb
  tag: 0.0.268
  logLevel: info
  resources: {}

fnserver:
  image: fnproject/fnserver
  tag: 0.3.461
  logLevel: info
  resources: {}
  nodeSelector: {}
  tolerations: []

ui:
  enabled: true
  fnui:
    image: fnproject/ui
    tag: 0.0.26
    resources: {}
  flowui:
    image: fnproject/flow
    tag: ui
    resources: {}
  service:
    flowuiPort: 3000
    fnuiPort: 80
    type: LoadBalancer
    annotations: {}

flow:
  image: fnproject/flow
  tag: 0.1.83
  logLevel: info
  service:
    port: 80
    type: ClusterIP
    annotations: {}
  resources: {}

##
##
mysql:
  persistence:
    enabled: false
    nodeSelector: mysql-storage
    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    # storageClass:
    storageClass: mysql
    accessMode: ReadWriteOnce
    size: 8Gi

  mysqlDatabase: fndb
  mysqlUser: fnapp
  mysqlPassword: boomsauce

##
##
redis:
  persistence:
    enabled: false
    nodeSelector: redis-storage
    storageClass: redis
    accessMode: ReadWriteOnce
    size: 8Gi
  usePassword: false

##
ingress:
  enabled: false

rbac:
  enabled: false

So Is there any know issue on this?

**Comment by chatchai-komrangded** [comment] 2018-06-17 14:07
Here's Log from "my-release-fn-fnlb-depl-8f8fcf476-4pvmh"  Pod below:

panic: unknown (get pods)
 goroutine 26 [running]:
github.com/fnproject/fn/fnlb/lb.(*k8sStore).watch(0xc420300ea0, 0xc4202ac220, 0x7, 0x7ffe4b73a3b1, 0x21, 0x50)
	/go/src/github.com/fnproject/fn/fnlb/lb/k8s_store.go:144 +0xb5e
created by github.com/fnproject/fn/fnlb/lb.NewK8sStore
	/go/src/github.com/fnproject/fn/fnlb/lb/k8s_store.go:56 +0x20e

**Comment by vjroxvijay1** [comment] 2018-06-26 17:44
Even I am facing the exact same issue today.

**Comment by zootalures** [comment] 2018-06-26 18:55
Can you try with:

```
rbac:
  enabled: true
```
in values.yaml?

**Comment by zootalures** [comment] 2018-06-26 19:34
Appologies, both - i think this was caused by RBAC being disalbed by default in the helm chart (https://github.com/fnproject/fn-helm/pull/32)  and the error message when the LB scans for Fn pods being unclear : https://github.com/fnproject/lb/pull/13

**Comment by vjroxvijay1** [comment] 2018-06-26 19:42
Thank you for helping us resolve the issue. That error seems to be gone now. However, I see the following error in load balancer logs.

time="2018-06-26T19:38:32Z" level=error msg="Unable to check API version" error="Get http://10.42.2.43:80/version: dial tcp 10.42.2.43:80: getsockopt: connection refused" node="10.42.2.43:80" 

I see all other PODS are up and running successfully

**Comment by vjroxvijay1** [comment] 2018-06-26 19:48
It looks like all three fn-api's in the cluster is refusing to connect at :80 with fn load balancer.

**Comment by vjroxvijay1** [comment] 2018-06-27 15:11
This issue can be closed as eventually the load balancer determined the nodes are healthy.

**Comment by zootalures** [comment] 2018-06-27 15:59
Thanks - and thanks for helping fix the issue!

**Closed by zootalures** 2018-06-27 15:59 UTC
